package transport

import "sync"

// minedRelayMessagePool reuses MinedRelayMessage structs across Unmarshal
// calls on the consumer hot path. Each incoming Redis stream message
// allocates one struct on the heap (the pointer escapes via the
// StreamMessage wrapper and the msgCh channel). At 200+ RPS this is pure
// GC churn that the pool eliminates.
//
// Pool ownership rules:
//
//  1. Acquire returns a zeroed message. Never trust its contents.
//  2. The caller owns the message until Release is called.
//  3. Release MUST run on every code path after the worker has finished
//     reading the message (success OR error). The Release call calls
//     Reset() which zeros every field, so no cross-request data can
//     leak between pool users.
//  4. After Release, the caller must treat the pointer as invalid. Any
//     downstream code that still needs data from the message must copy
//     it out before Release runs.
var minedRelayMessagePool = sync.Pool{
	New: func() any { return new(MinedRelayMessage) },
}

// AcquireMinedRelayMessage returns a zeroed MinedRelayMessage from the
// pool, ready to be Unmarshaled into. Callers must Release the message
// when done to avoid losing the pooling win.
func AcquireMinedRelayMessage() *MinedRelayMessage {
	return minedRelayMessagePool.Get().(*MinedRelayMessage)
}

// ReleaseMinedRelayMessage resets m and returns it to the pool. It is
// safe to call with a nil pointer. After calling Release, the caller
// must not touch m again — a subsequent Acquire on another goroutine
// may hand the same pointer out with fresh data.
func ReleaseMinedRelayMessage(m *MinedRelayMessage) {
	if m == nil {
		return
	}
	// Reset() is generated by gogoproto and zeros every field, including
	// the RelayHash/RelayBytes slice headers. Without Reset the next user
	// would see stale strings from the previous relay.
	m.Reset()
	minedRelayMessagePool.Put(m)
}
